// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "campaign": customerService Resource Client
//
// Command:
// $ goagen
// --design=campaign/design
// --out=$(GOPATH)/src/campaign
// --version=v1.3.0

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateCustomerServicePath computes a request path to the create action of customerService.
func CreateCustomerServicePath() string {

	return fmt.Sprintf("/customerservcie/")
}

// informs the customer service when a customer replies for an sms
func (c *Client) CreateCustomerService(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewCreateCustomerServiceRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateCustomerServiceRequest create the request corresponding to the create action endpoint of the customerService resource.
func (c *Client) NewCreateCustomerServiceRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
