// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "campaign": swagger TestHelpers
//
// Command:
// $ goagen
// --design=campaign/design
// --out=$(GOPATH)/src/campaign
// --version=v1.3.0

package test
