// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "campaign": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=campaign/design
// --out=$(GOPATH)/src/campaign
// --regen=true
// --version=v1.3.0

package app
